### ISSUE TITLE
训练显存爆了

### ISSUE THREAD

**Issue by SunnyLee151064** [gunny97/MEMTO#2]
训练过程中是不是有内存泄漏的问题？显存占用一直上涨最后就崩掉了

**Comment by gunny97** [comment]
I worked in a multi-GPU environment. If you only work with a single GPU, there might be a memory issue in the vram size.

**Comment by shiyu5feng** [comment]
> 训练过程中是不是有内存泄漏的问题？显存占用一直上涨最后就崩掉了

请问你训练好这个模型了吗？为什么我这里报错？是代码有问题吗？
![Uploading 屏幕截图 2024-02-04 175443.png…]()

**Comment by shiyu5feng** [comment]
![屏幕截图 2024-02-04 175443](https://github.com/gunny97/MEMTO/assets/130022822/ccd326df-bcd0-4eb7-8c8c-daac4ae0bf1d)

**Comment by Yangguifei1** [comment]
> ![屏幕截图 2024-02-04 175443](https://private-user-images.githubusercontent.com/130022822/302093598-ccd326df-bcd0-4eb7-8c8c-daac4ae0bf1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NDQ1NjAsIm5iZiI6MTcxMjg0NDI2MCwicGF0aCI6Ii8xMzAwMjI4MjIvMzAyMDkzNTk4LWNjZDMyNmRmLWJjZDAtNGViNy04YzhjLWRhYWM0YWUwYmYxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQxNDA0MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYjAzN2U0ZDU2MmRjNGVlYWQ1ODI4YWQxMGQ3OTI2NDBhNDY4YTYwNzZmMzRjNWJmYWYxMDkyYzk2OGJiODBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.F2rdLOZytPmUKHFcKG7eRd0P0X1pi4S9pOIQWIE8ztU)

请问您这个问题解决了吗

**Comment by SunnyLee151064** [comment]
没有，自己尝试着写了一个很简单的demo没啥效果，就没再研究了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月11日(周四) 晚上10:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [gunny97/MEMTO] 训练显存爆了 (Issue #2)




  

  
请问您这个问题解决了吗
